name: AI Tech News

permissions:
  contents: write
  
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          QWEN_API_KEY: ${{ secrets.QWEN_API_KEY }}
        run: |
          python scripts/main.py

      - name: Commit report
        run: |
          git config --global user.name "AI Bot"
          git config --global user.email "bot@example.com"
          git add README.md
          git commit -m "update news" || echo "no changes"
          git push
